Feature room
0xOnyx/42_ft_transcendence pull request #66
Opened 2023-04-29 10:18 UTC by 0xOnyx

add feature to chat with channel not merge is in dev pls !

2023-04-29 15:03 UTC, danielthalmann requested changes
La migration précédente doit être toujours être présente. Il faut un nouveau fichier de migration qui contient que les modifications supplémentaires de la base de donnée. 
Tout ceci est expliqué ici : https://www.prisma.io/docs/concepts/components/prisma-migrate/get-started
Il faut refaire cette partie sinon, on est à nouveau embêté avec la base de donnée.

2023-04-30 18:57 UTC, 0xOnyx commented
Please do not merge, as it's still a draft

2023-05-06 10:00 UTC, danielthalmann approved these changes

2023-05-06 10:02 UTC, danielthalmann commented
J'ai modifié la migration pour être propre. Le code est fonctionnel. Il y a quelque manière de faire au niveau de la fonctionnalité à rediscuter. Ok pour un merge

2023-05-06 11:39 UTC, merged